blog/backweb/urls.py
from django.conf.urls import url

from backweb import views

urlpatterns = [
    # 首页
    url(r'^index/', views.index, name='index'),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 添加用户
    url(r'^add_user', views.add_user, name='add_user'),
    # 注销
    url(r'^logout/', views.logout, name='logout'),
    # 修改密码
    url(r'^update_pwd/(\d+)', views.update_pwd, name='update_pwd'),
    # 管理用户
    url(r'^manage_admin/', views.manage_admin, name='manage_admin'),
    # 后台系统首页
    url(r'^article/', views.article, name='article'),
    # 增加文章
    url(r'^add_article/', views.add_article, name='add_article'),
    # 修改文章
    url(r'^update_article/(\d+)/', views.update_article, name='update_article'),
    # 删除文章
    url(r'^delete_article/(\d+)/', views.delete_article, name='delete_article'),
    # 删除全部文章
    url(r'^delete_all/', views.delete_all, name='delete_all'),
    # 评论首页
    url(r'^comment/', views.comment, name='comment'),
    # 添加评论
    url(r'^add_comment/', views.add_comment, name='add_comment'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static


from django.contrib import admin
from blog.settings import MEDIA_URL, MEDIA_ROOT

from utils.upload_images import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 引入web的路由urls.py文件
    url(r'^web/', include('web.urls', namespace='web')),
    # 引入backblog的路由urls.py文件
    url(r'^backweb/', include('backweb.urls', namespace='back')),
    # kindeditor编辑器上传图片地址
    url(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

# 告诉django，解析media文件夹中的静态文件
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/web/urls.py
from django.conf.urls import url

from web import views

urlpatterns = [
    # 首页
    url(r'^index/', views.index, name='index'),
    # 博客内容
    url(r'^info/(\d+)', views.info, name='info'),
]

blog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
           首页_{{ admin.username }}个人博客 - 一个站在web前端设计之路的技术员个人博客网站
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">{{ admin.username }}个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'web:index' %}">网站首页</a></li>
      <li><a href="list.html">我的日记</a></li>
      <li><a href="about.html">关于我</a></li>
      <li><a href="gbook.html">留言</a></li>
      <li><a href="info.html">内容页</a></li>
      <li><a href="{% url 'back:index' %}">博客后台</a></li>
    </ul>
</nav>
</header>
   {% block content %}
   {% endblock %}

  {% block js %}
  {% endblock %}
</body>
</html>

blog/templates/web/index.html
  {% extends 'web/base.html' %}

  {% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
  {% endblock %}

{% block content %}
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/web/image/4.jpg"></i>
          <p><b>{{ admin.username }}</b>一个专注于守护世界和平的人</p>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          <li><a href="/">学无止境（33）</a></li>
          <li><a href="/">日记（19）</a></li>
          <li><a href="/">慢生活（520）</a></li>
          <li><a href="/">美文欣赏（40）</a></li>
        </ul>
      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我</h2>
        <ul>
          <img src="/static/web/image/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
    {% for page in pages %}
    <li><i><a href="/"><img src="/media/{{ page.icon }}" alt=""></a></i>
      <h3><a href="{% url 'web:info' page.id %}">{{ page.title }}</a></h3>
      <p>{{ page.desc }}</p>
    </li>
    {% endfor %}
    <div class="pagelist">
      {% if pages.has_previous %}
          <a href="{% url 'art:art_list' %}?page={{ pages.previous_page_number }}">上一页</a>
       {% else %}
          <a href="">上一页</a>
       {% endif %}
      {% for i in pages.paginator.page_range %}
        <a href="{% url 'web:index' %}?page={{ i }}" class="curPage">{{ i }}</a>
      {% endfor %}
      {% if pages.has_next %}
          <a href="{% url 'art:art_list' %}?page={{ pages.next_page_number }}">下一页</a>
       {% else %}
       <a href="">下一页</a>
       {% endif %}
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http:/www.yangqq.com" target="_blank">{{ admin.username }}个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

{% block js %}
<script src="/static/web/js/jquery.min./js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm./js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr./js"></script>
<![endif]-->
{% endblock %}

blog/templates/web/info.html
{% extends 'web/base.html' %}

{% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/info.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block content %}
<article>
  <aside class="l_box">
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>
    <div class="tuijian">
      <h2>站长推荐</h2>
      <ul>
        <li><a href="/">你是什么人便会遇上什么人</a></li>
        <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        <li><a href="/">你是什么人便会遇上什么人</a></li>
        <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="/">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
    <div class="tuijian">
      <h2>点击排行</h2>
      <ul>
        <li><a href="/">你是什么人便会遇上什么人</a></li>
        <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        <li><a href="/">你是什么人便会遇上什么人</a></li>
        <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="/">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
    <div class="cloud">
      <h2>标签云</h2>
      <ul>
        <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/image/wx.jpg">
      </ul>
    </div>
  </aside>
  <main>
    <div class="infosbox">
      <div class="newsview">
        <h3 class="news_title">{{ article.title }}</h3>
        <div class="bloginfo">
          <ul>
            <li class="author">作者：<a href="/">{{ article.blogger }}</a></li>
            <li class="lmname"><a href="/">学无止境</a></li>
            <li class="timer">时间：{{ article.create_time.year }}-{{ article.create_time.month }}-{{ article.create_time.day }}</li>
            <li class="view">0人已阅读</li>
          </ul>
        </div>
        <div class="tags"><a href="/" target="_blank">个人博客</a> &nbsp; <a href="/" target="_blank">小世界</a></div>
        <div class="news_about"><strong>简介</strong>{{ article.desc }}</div>
        <div class="news_con">{{ article.content | safe }}</div>
      </div>
      <div class="share">
        <p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>13</b>)</p>
      </div>
      <div class="nextinfo">
        <p>上一篇：<a href="/news/life/2018-03-13/804.html">作为一个设计师,如果遭到质疑你是否能恪守自己的原则?</a></p>
        <p>下一篇：<a href="/news/life/">返回列表</a></p>
      </div>
      <div class="news_pl">
        <h2>文章评论</h2>
        <div class="gbko"> 
          <script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>
          {% for comment in comments %}
            {% if comment.comment_article.id == article.id %}
              <div class="fb">
                <ul>
                  <p class="fbtime"><span>{{ comment.create_time }}</span>{{ comment.comment_admin.username }}</p>
                  <p class="fbinfo">{{ comment.content }}</p>
                </ul>
              </div>
            {% endif %}
          {% endfor %}
          <form action="{% url 'back:add_comment' %}" method="post" name="saypl" id="saypl" onsubmit="return CheckPl(document.saypl)">
            {% csrf_token %}
            <div id="plpost">
              <input type="hidden" name="article_id" value="{{ article.id }}">
              <p class="saying"><span><a href="/e/pl/?classid=77&amp;id=106">共有<script type="text/javascript" src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>{{ comments.count }}条评论</a></span>来说两句吧...</p>
              <p class="yname" ><span>用户名:</span>
                <input name="user" type="text" class="inputText" id="username" value="" size="16">
              </p>
              <p class="yzm"><span>密码:</span>
                <input name="password" type="password" class="inputText" size="16">
                <p style="color:red">{{ error }}</p>
              </p>
              <input name="nomember" type="hidden" id="nomember" value="1" checked="checked">
              <textarea rows="6" name="comment_text"></textarea>
              <input name="imageField" type="submit" value="提交">
              <input name="id" type="hidden" id="id" value="106">
              <input name="classid" type="hidden" id="classid" value="77">
              <input name="enews" type="hidden" id="enews" value="AddPl">
              <input name="repid" type="hidden" id="repid" value="0">
              <input type="hidden" name="ecmsfrom" value="/joke/talk/2018-07-23/106.html">
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

{% block js %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
          <script>
		  function CheckPl(obj)
		  {
		  if(obj.saytext.value=="")
		  {
		  alert("您没什么话要说吗？");
		  obj.saytext.focus();
		  return false;
		  }
		  return true;
		  }
		  </script>
{% endblock %}