blog/backweb/urls.py
from django.conf.urls import url

from backweb import views

urlpatterns = [
    # 首页
    url(r'^index/', views.index, name='index'),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 添加用户
    url(r'^add_user', views.add_user, name='add_user'),
    # 注销
    url(r'^logout/', views.logout, name='logout'),
    # 修改密码
    url(r'^update_pwd/(\d+)', views.update_pwd, name='update_pwd'),
    # 管理用户
    url(r'^manage_admin/', views.manage_admin, name='manage_admin'),
    # 后台系统首页
    url(r'^article/', views.article, name='article'),
    # 增加文章
    url(r'^add_article/', views.add_article, name='add_article'),
    # 修改文章
    url(r'^update_article/(\d+)/', views.update_article, name='update_article'),
    # 删除文章
    url(r'^delete_article/(\d+)/', views.delete_article, name='delete_article'),
    # 删除全部文章
    url(r'^delete_all/', views.delete_all, name='delete_all'),
    # 评论首页
    url(r'^comment/', views.comment, name='comment'),
    # 添加评论
    url(r'^add_comment/', views.add_comment, name='add_comment'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static


from django.contrib import admin
from blog.settings import MEDIA_URL, MEDIA_ROOT

from utils.upload_images import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 引入web的路由urls.py文件
    url(r'^web/', include('web.urls', namespace='web')),
    # 引入backblog的路由urls.py文件
    url(r'^backweb/', include('backweb.urls', namespace='back')),
    # kindeditor编辑器上传图片地址
    url(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

# 告诉django，解析media文件夹中的静态文件
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/web/urls.py
from django.conf.urls import url

from web import views

urlpatterns = [
    # 首页
    url(r'^index/', views.index, name='index'),
    # 博客内容
    url(r'^info/(\d+)', views.info, name='info'),
]

blog/backweb/models.py
from django.db import models

# Create your models here.


class Admin(models.Model):
    user = models.CharField(max_length=20, unique=True)
    username = models.CharField(max_length=20)
    sex = models.BooleanField(default=1)
    userpassword = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    mail = models.EmailField(max_length=20)

    class Meta:
        db_table = 'admin'


class Article(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=150)
    content = models.TextField()
    icon = models.ImageField(upload_to='article', null=True)
    keywords = models.CharField(max_length=10)
    blogger = models.CharField(max_length=10, null=True)
    publish = models.BooleanField(default=1)
    Publisher = models.ForeignKey(Admin, null=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'article'


class Comment(models.Model):
    content = models.CharField(max_length=100)
    create_time = models.DateTimeField(auto_now_add=True)
    comment_article = models.ForeignKey(Article, null=True)
    comment_admin = models.ForeignKey(Admin, null=True)

    class Meta:
        db_table = 'comment'

blog/backweb/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import HttpResponseRedirect
from backweb.models import Admin, Article, Comment
from django.urls import reverse
from backweb.Artform import AddArtForm, UpdatePwd

# Create your views here.


def index(request):
    # 首页
    if request.method == 'GET':
        admin = request.admin
        articles = Article.objects.all()
        p = Paginator(articles, 5)
        return render(request, 'backweb/index.html', {'admin': admin, 'p': p})


def login(request):
    # 登陆
    if request.method == 'GET':
        return render(request, 'backweb/login.html')
    if request.method == 'POST':
        user = request.POST.get('user')
        password = request.POST.get('userpwd')
        admin = Admin.objects.filter(user=user, userpassword=password).first()
        if admin:
            request.session['admin_id'] = admin.id
            res = HttpResponseRedirect(reverse('back:index'))
            return res
        else:
            err_name_pwd = '用户名或密码错误！'
            return render(request, 'backweb/login.html', {'err_name_pwd': err_name_pwd})


def add_user(request):
    if request.method == 'GET':
        return render(request, 'backweb/manage-user.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        user = request.POST.get('user')
        phone = request.POST.get('phone')
        mail = request.POST.get('mail')
        user_password = request.POST.get('password')
        Admin.objects.create(username=username, user=user, phone=phone, mail=mail, user_password=user_password)
        return render(request, 'backweb/manage-user.html')


def logout(request):
    # 注销
    del request.session['admin_id']
    return HttpResponseRedirect('/login/')


def update_pwd(request, id):
    if request.method == 'GET':
        return render(request, 'backweb/index.html')
    if request.method == 'POST':
        form = UpdatePwd(request.POST)
        if form.is_valid():
            admin = Admin.objects.filter(pk=id).first()
            username = form.cleaned_data['username']
            user = form.cleaned_data['user']
            phone = form.cleaned_data['phone']
            userpassword = form.cleaned_data['userpassword']
            new_one_password = form.cleaned_data['new_one_password']
            new_tow_password = form.cleaned_data['new_tow_password']
            if new_one_password == new_tow_password:
                admin.username = username
                admin.user = user
                admin.phone = phone
                admin.userpassword = userpassword
                admin.save()
            else:
                return render(request, 'backweb/index.html', {'err': '两次密码不一致'})
        else:
            return render(request, 'backweb/index.html', {'form': form})


def article(request):
    # 显示页面
    if request.method == 'GET':
        admin = request.admin
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        paginator = Paginator(articles, 5)
        page = paginator.page(page)
        return render(request, 'backweb/article.html', {'admin': admin, 'page': page})


def add_article(request):
    # 创建文章
    admin = request.admin
    if request.method == 'GET':
        return render(request, 'backweb/add-article.html', {'admin': admin})
    if request.method == 'POST':
        form = AddArtForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            keywords = form.cleaned_data['keywords']
            blogger = form.cleaned_data['blogger']
            publish = form.cleaned_data['publish']
            Article.objects.create(
                title=title, desc=desc, content=content, icon=icon, keywords=keywords, blogger=blogger, publish=publish
            )
            # 创建文章返回列表页面
            return HttpResponseRedirect(reverse('back:article'))
        else:
            return render(request, 'backweb/add-article.html', {'form': form, 'admin': admin})


def update_article(request, id):
    #  修改文章
    admin = request.admin
    article = Article.objects.filter(pk=id).first()
    if request.method == 'GET':
        return render(request, 'backweb/add-article.html', {'article': article, 'admin': admin})
    if request.method == 'POST':
        form = AddArtForm(request.POST, request.FILES)
        if form.is_valid():
            # 验证成功
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            keywords = form.cleaned_data['keywords']
            blogger = form.cleaned_data['blogger']
            publish = form.cleaned_data['publish']
            article.title = title
            article.desc = desc
            article.content = content
            article.blogger = blogger
            if publish:
                publish = 1
            else:
                publish = 0
            article.publish = publish
            if icon:
                article.icon = icon
            article.keywords = keywords
            article.save()
            return HttpResponseRedirect(reverse('back:article'))
        else:
            # 验证失败
            return render(request, 'backweb/add-article.html', {'form': form, 'article': article, 'admin': admin})


def delete_article(request, id):
    # 删除文章
    if request.method == 'GET':
        Article.objects.filter(pk=id).delete()
        return HttpResponseRedirect(reverse('back:article'))


def delete_all(request):
    # 删除全部文章
    if request.method == 'GET':
        pass


def manage_admin(request):
    # 用户管理
    admin = request.admin
    if request.method == 'GET':
        admins = Admin.objects.all()
        return render(request, 'backweb/manage-user.html', {'admin': admin, 'admins': admins})


def comment(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        comment = Comment.objects.all()
        paginator = Paginator(comment, 5)
        page = paginator.page(page)
        return render(request, 'backweb/comment.html', {'pages': page})


def add_comment(request):
    if request.method == 'GET':
        return render(request, 'backweb/comment.html')
    if request.method == 'POST':
        user = request.POST.get('user')
        password = request.POST.get('password')
        id = int(request.POST.get('article_id'))
        article = Article.objects.filter(pk=id).first()
        admin = Admin.objects.filter(user=user, userpassword=password).first()
        if admin:
            content = request.POST.get('comment_text')
            Comment.objects.create(content=content, comment_admin=admin, comment_article=article)
            return HttpResponseRedirect(reverse('back:comment'))
        else:
            error = '用户名或密码错误！'
            return render(request, 'web/info.html', {'error': error})

blog/templates/backweb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body class="user-select">
     {% block content %}
     {% endblock %}
     {% block js %}
     {% endblock %}
</body>
</html>

blog/templates/backweb/bases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
           {{ admin.username }}的管理系统
        {% endblock %}
    </title>
    {% block css %}
       <link rel="stylesheet" type="text/css" href="/static/backweb/css/bootstrap.min.css">
       <link rel="stylesheet" type="text/css" href="/static/backweb/css/style.css">
       <link rel="stylesheet" type="text/css" href="/static/backweb/css/font-awesome.min.css">
       <link rel="apple-touch-icon-precomposed" href="image/icon/icon.png">
       <link rel="shortcut icon" href="/static/backweb/image/icon/favicon.ico">
    {% endblock %}
</head>
<body class="user-select">
  <section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <!--<span class="badge">1</span>-->
            <li><a href="{% url 'web:index' %}">博客主页</a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ admin.username }}<span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'back:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">注销</a></li>
            <li><a data-toggle="modal" href="{% url 'web:index' %}" data-target="#WeChat">我的博客</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="{% url 'back:index' %}">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'back:article' %}">文章</a></li>
        <li><a href="">公告</a></li>
        <li><a href="{% url 'back:comment' %}">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="bottom" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="">友情链接</a></li>
            <li><a data-toggle="modal" data-target="#areDeveloping">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a data-toggle="modal" data-target="#areDeveloping">管理用户组</a></li>
            <li><a href="{% url 'back:manage_admin' %}">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="loginlog.html">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="setting.html">基本设置</a></li>
            <li><a href="readset.html">阅读设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a data-toggle="modal" data-target="#areDeveloping">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
   {% block bottom %}

   {% endblock %}
  </section>
  {% block content %}
  <!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="{{ admin.username }}" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="{{ admin.user }}" class="form-control" name="user" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="{{ admin.phone }}" class="form-control" name="phone" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="userpassword" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_one_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_tow_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary" id="submit">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="/static/backweb/image/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="/static/backweb/image/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
  {% endblock %}

  {% block js %}
     <!--<script src="/static/backweb/js/jquery-2.1.4.min.js"></script>-->
     <!--<script type="text/script">-->
         <!--$(function(){-->
				<!--$.ajax({-->
					<!--type: "POST",-->
					<!--url: "/Article/delete",-->
					<!--data: "id=" + id,-->
					<!--cache: false, //不缓存此页面-->
					<!--success: function (data) {-->
						<!--window.location.reload();-->
					<!--}-->
				<!--});-->
         <!--});-->
     <!--</script>-->
  {% endblock %}
</body>
</html>

blog/templates/backweb/comment.html
{% extends 'backweb/bases.html' %}
    {% block title %}
       {{ block.super }}
    {% endblock %}

    {% block bottom %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="/Comment/checkAll" method="post">
        <h1 class="page-header">管理 <span class="badge">4</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">标题</span></th>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">评论者</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">摘要</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
            {% for page in pages %}
              <tr>
                <td><a href="{% url 'web:info' page.comment_article.id %}">{{ page.comment_article.title }}</a></td>
                <td>{{ page.comment_admin.username }}</td>
                <td class="article-title">{{ page.content }}</td>
                <td>{{ page.create_time.year }}-{{ page.create_time.month }}-{{ page.create_time.day }}</td>
                <td><a rel="1" name="see">查看</a> <a rel="1" name="delete">删除</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
              <li class="disabled"><a aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a> </li>
              <li class="active"><a>1</a></li>
              <li class="disabled"><a aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
            </ul>
          </nav>
        </footer>
      </form>
    </div>
  </div>
  {% endblock %}
  {% block content %}
  {{ block.super }}
<!--查看评论模态框-->
<div class="modal fade" id="seeComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >查看评论</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">评论ID:</td>
                <td width="80%" class="see-comment-id"></td>
              </tr>
              <tr>
                <td wdith="20%">评论页面:</td>
                <td width="80%" class="see-comment-page"></td>
              </tr>
              <tr>
                <td wdith="20%">评论内容:</td>
                <td width="80%" class="see-comment-content"></td>
              </tr>
              <tr>
                <td wdith="20%">IP:</td>
                <td width="80%" class="see-comment-ip"></td>
              </tr>
              <tr>
                <td wdith="20%">所在地:</td>
                <td width="80%" class="see-comment-address"></td>
              </tr>
              <tr>
                <td wdith="20%">系统:</td>
                <td width="80%" class="see-comment-system"></td>
              </tr>
              <tr>
                <td wdith="20%">浏览器:</td>
                <td width="80%" class="see-comment-browser"></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
        </div>
      </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="/static/backweb/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
<script src="/static/backweb/js/bootstrap.min.js"></script>
<script src="/static/backweb/js/admin-scripts.js"></script>
<script>
$(function () {
    $("#main table tbody tr td a").click(function () {
        var name = $(this);
        var id = name.attr("rel"); //对应id   
        if (name.attr("name") === "see") {
            $.ajax({
                type: "POST",
                url: "/Comment/see",
                data: "id=" + id,
                cache: false, //不缓存此页面   
                success: function (data) {
                    var data = JSON.parse(data);
                    $('.see-comment-id').html(data.id);
                    $('.see-comment-page').html(data.page);
                    $('.see-comment-content').html(data.content);
                    $('.see-comment-ip').html(data.ip);
                    $('.see-comment-address').html(data.address);
                    $('.see-comment-system').html(data.system);
                    $('.see-comment-browser').html(data.browser);
                    $('#seeComment').modal('show');
                }
            });
        } else if (name.attr("name") === "delete") {
            if (window.confirm("此操作不可逆，是否确认？")) {
                $.ajax({
                    type: "POST",
                    url: "/Comment/delete",
                    data: "id=" + id,
                    cache: false, //不缓存此页面   
                    success: function (data) {
                        window.location.reload();
                    }
                });
            };
        };
        return false;
    });
});
</script>
{% endblock %}